### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by flozano** [junegunn/fzf#2293]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
This happened once, I can't reproduce again, when completing zsh:
```
~ ❯ cd Projects/puppet/p<tab>
panic: runtime error: index out of range [-1]

                                             goroutine 20 [running]:
                                                                    github.com/junegunn/fzf/src.(*Merger).mergedGet(0xc000238000, 0xffffffffffffffff, 0x0, 0x0)
                      	/private/tmp/fzf-20201206-61995-5cauzh/fzf-0.24.4/src/merger.go:120 +0x39d
                                                                                                  github.com/junegunn/fzf/src.(*Merger).Get(0xc000238000, 0xffffffffffffffff, 0x0, 0x0)
                                              	/private/tmp/fzf-20201206-61995-5cauzh/fzf-0.24.4/src/merger.go:72 +0xd0
                                                                                                                        github.com/junegunn/fzf/src.(*Terminal).Loop.func12(0xc000213a78)
                                                	/private/tmp/fzf-20201206-61995-5cauzh/fzf-0.24.4/src/terminal.go:2133 +0x65
                                                                                                                                    github.com/junegunn/fzf/src.(*Terminal).Loop.func15(0x1e, 0x0, 0x0, 0x1c, 0x1011df7)
                                                                               	/private/tmp/fzf-20201206-61995-5cauzh/fzf-0.24.4/src/terminal.go:2300 +0x5e2
                    github.com/junegunn/fzf/src.(*Terminal).Loop.func14(0xc00011a780, 0x1, 0x1, 0x1c, 0xc000139d00)
                                                                                                                   	/private/tmp/fzf-20201206-61995-5cauzh/fzf-0.24.4/src/terminal.go:2167 +0x86
                                                           github.com/junegunn/fzf/src.(*Terminal).Loop(0xc00018a480)
                                                                                                                     	/private/tmp/fzf-20201206-61995-5cauzh/fzf-0.24.4/src/terminal.go:2534 +0xcce
                                                            created by github.com/junegunn/fzf/src.Run
                                                                                                      	/private/tmp/fzf-20201206-61995-5cauzh/fzf-0.24.4/src/core.go:220 +0xad4
```

with latest version from homebrew

**Comment by junegunn** [comment]
Thanks for the report. Can you show your fzf-related variables?

```sh
env | grep FZF
```

**Comment by junegunn** [comment]
I also can't find a way to reproduce the problem. But I just pushed a commit that should fix the problem. Thanks.

**Comment by flozano** [comment]
Thanks!

I don't have any FZF var, so I guess everything is "by default":
```
~ ❯ env | grep FZF

~ ❯
```
