### ISSUE TITLE
`fzf --ansi` crashes for ansi escape sequence [0K

### ISSUE THREAD

**Issue by iyzana** [junegunn/fzf#2339]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (0.25.0 (8c533e3))
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

```
echo '^[[0K' | fzf --ansi
```
note that the leading `^[` needs to be inserted by typing `<C-V><Esc>`

output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x4f829a]

goroutine 18 [running]:
github.com/junegunn/fzf/src.interpretCode(0xc000016130, 0x4, 0x0, 0x0)
	/Users/jg/gdrive/sync/projects/fzf/src/ansi.go:205 +0x4fa
github.com/junegunn/fzf/src.extractColor(0xc000016130, 0x4, 0x0, 0x0, 0xc000016130, 0x4, 0x8, 0xc00000e010)
	/Users/jg/gdrive/sync/projects/fzf/src/ansi.go:151 +0x35d
github.com/junegunn/fzf/src.Run.func2(0xc000016128, 0x4, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc00000e010)
	/Users/jg/gdrive/sync/projects/fzf/src/core.go:72 +0xaa
github.com/junegunn/fzf/src.Run.func4(0xc000076000, 0xc000016128, 0x4, 0x5, 0x1)
	/Users/jg/gdrive/sync/projects/fzf/src/core.go:97 +0x1e8
github.com/junegunn/fzf/src.(*Chunk).push(...)
	/Users/jg/gdrive/sync/projects/fzf/src/chunklist.go:30
github.com/junegunn/fzf/src.(*ChunkList).Push(0xc000098810, 0xc000016128, 0x4, 0x5, 0x0)
	/Users/jg/gdrive/sync/projects/fzf/src/chunklist.go:62 +0x110
github.com/junegunn/fzf/src.Run.func6(0xc000016128, 0x4, 0x5, 0x5)
	/Users/jg/gdrive/sync/projects/fzf/src/core.go:142 +0x48
github.com/junegunn/fzf/src.(*Reader).feed(0xc0000c04c0, 0x5b5660, 0xc0000bc000)
	/Users/jg/gdrive/sync/projects/fzf/src/reader.go:139 +0xf5
github.com/junegunn/fzf/src.(*Reader).readFromStdin(...)
	/Users/jg/gdrive/sync/projects/fzf/src/reader.go:150
github.com/junegunn/fzf/src.(*Reader).ReadSource(0xc0000c04c0)
	/Users/jg/gdrive/sync/projects/fzf/src/reader.go:114 +0x128
created by github.com/junegunn/fzf/src.Run
	/Users/jg/gdrive/sync/projects/fzf/src/core.go:144 +0x1372
```

## Additional info

i first encountered the issue when trying to open the lines view in nvim while the following file was in scope:
https://github.com/alacritty/alacritty/blob/dbd8538762ef8968a493e1bf996e8693479ca783/alacritty_terminal/tests/ref/vttest_cursor_movement_1/alacritty.recording

i ran `unset FZF_DEFAULT_OPTS` before

first bad commit is https://github.com/junegunn/fzf/commit/3829eab1cf572d26e12dd5d96b1700c07c2905fc

my guess is that it crashes when there is no color to clear

**Comment by junegunn** [comment]
Thanks for the report, let me look into it.

```sh
echo -e '\x1b[0K' | fzf --ansi
```

**Comment by junegunn** [comment]
Should be fixed now. Thanks!

**Comment by iyzana** [comment]
And thank you for your awesome work!
