### ISSUE TITLE
Panic on tiebreak=chunk with query like `!0`

### ISSUE THREAD

**Issue by lincheney** [junegunn/fzf#3055]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Run the following
`echo 1 | fzf --tiebreak=chunk`
Then type `!0` into the query
This results in fzf crashing with the following:
```
panic: runtime error: index out of range [65534] with length 1                                                                     

goroutine 7 [running]:
github.com/junegunn/fzf/src/util.(*Chars).Get(...)
    /Users/jg/github/fzf/src/util/chars.go:88
github.com/junegunn/fzf/src.buildResult(0xc000069800, {0xc000016590?, 0x7f38352ff108?, 0x70?}, 0x0)
    /Users/jg/github/fzf/src/result.go:57 +0x770
github.com/junegunn/fzf/src.(*Pattern).MatchItem(0xc000314120, 0xc000026d68?, 0xe6?, 0x6dccc0?)
    /Users/jg/github/fzf/src/pattern.go:325 +0xa5
github.com/junegunn/fzf/src.(*Pattern).matchChunk(0xc000314120, 0xc000069800, {0x0?, 0x7f38352ff108?, 0x18?}, 0xc00002e800?)
    /Users/jg/github/fzf/src/pattern.go:307 +0x105
github.com/junegunn/fzf/src.(*Pattern).Match(0xc000314120, 0xc000016248?, 0x53bca0?)
    /Users/jg/github/fzf/src/pattern.go:294 +0x98
github.com/junegunn/fzf/src.(*Matcher).scan.func1(0x0, 0x1?, {0xc000012020, 0x1, 0xc0000c8320?})
    /Users/jg/github/fzf/src/matcher.go:168 +0x178
    created by github.com/junegunn/fzf/src.(*Matcher).scan
    /Users/jg/github/fzf/src/matcher.go:163 +0xaab
```

I have tested this with version `0.35.0 (d01ae55)`

**Comment by junegunn** [comment]
Fixed on master. Thanks for the report!
