### ISSUE TITLE
FZF Panics

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#666]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

```
fzf --version
0.15.0
```

```
runtime error: index out of range

goroutine 295 [running]:
panic(0x545a60, 0xc420010300)
    /go1.7/src/runtime/panic.go:500 +0x1a1
github.com/junegunn/fzf/src/algo.FuzzyMatchV2(0x100, 0xc420b5c000, 0x8b84, 0x9000, 0x0, 0x0, 0x0, 0xc4213657d0, 0x2, 0x2, ...)
    /fzf/gopath/src/github.com/junegunn/fzf/src/algo/algo.go:331 +0x964
github.com/junegunn/fzf/src.(*Pattern).iter(0xc421388400, 0x57aaf0, 0xc420d6a0c0, 0x1, 0x1, 0xc420d60100, 0xc4213657d0, 0x2, 0x2, 0xc420af3a00, ...)
    /fzf/gopath/src/github.com/junegunn/fzf/src/pattern.go:382 +0x106
github.com/junegunn/fzf/src.(*Pattern).extendedMatch(0xc421388400, 0xc420f16120, 0x0, 0xc4202d6330, 0x82e2e8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /fzf/gopath/src/github.com/junegunn/fzf/src/pattern.go:332 +0x29e
github.com/junegunn/fzf/src.(*Pattern).MatchItem(0xc421388400, 0xc420f16120, 0x0, 0xc4202d6330, 0x0, 0x0, 0x0, 0x0, 0x0)
    /fzf/gopath/src/github.com/junegunn/fzf/src/pattern.go:295 +0x72
github.com/junegunn/fzf/src.(*Pattern).matchChunk(0xc421388400, 0xc4201c5ea0, 0x0, 0x0, 0x0, 0xc4202d6330, 0x0, 0xc421383800, 0x0)
    /fzf/gopath/src/github.com/junegunn/fzf/src/pattern.go:278 +0x248
github.com/junegunn/fzf/src.(*Pattern).Match(0xc421388400, 0xc4201c5ea0, 0xc4202d6330, 0xc42151cb00, 0x1, 0x1)
    /fzf/gopath/src/github.com/junegunn/fzf/src/pattern.go:265 +0x20d
github.com/junegunn/fzf/src.(*Matcher).scan.func1(0xc421365810, 0xc4202d6300, 0xc421365800, 0xc4212ebc00, 0xc420016820, 0xc42137bc20, 0x17, 0xc4202d6330, 0xc4213920b8, 0x1, ...)
    /fzf/gopath/src/github.com/junegunn/fzf/src/matcher.go:167 +0xf6
    created by github.com/junegunn/fzf/src.(*Matcher).scan
    /fzf/gopath/src/github.com/junegunn/fzf/src/matcher.go:187 +0x305
```

```
echo "$FZF_DEFAULT_OPTS"
--history /home/edgar/.fzfhistory --bind='f4:toggle-all,ctrl-o:toggle-all,f1:execute@copy "$(echo {} | sed -r "s/^[0-9 ]+//")"@,ctrl-i:execute@copy "$(echo {} | sed -r "s/^[0-9 ]+//")"@,ctrl-t:execute@tmux new-window "vim {}" > /tmp/tm 2>&1@,ctrl-v:execute@tmux new-window "dvim e {}" > /tmp/tm 2>&1@,?:toggle-preview,ctrl-u:page-up,ctrl-d:page-down' --preview 'less <<< {}' --preview-window 'up:50%:hidden' --ansi --exit-0 --margin 5%,5% --multi
```

This happened by searching for a pattern, and then moving in the list. I don't remember whether I was at a specific place in the list.

**Comment by edi9999** [comment]
Here's a way to reproduce the issue : 

`v="$(yes 'a' | head -n 33000 | tr -d '\n')foobar"; echo "$v" | fzf`

**Comment by junegunn** [comment]
Sorry about that, let me fix it.

**Comment by junegunn** [comment]
0.15.1 is up. Thanks for the report.

**Comment by edi9999** [comment]
No problem! Thanks a lot :-).
