### ISSUE TITLE
panic: --header-lines=1

### ISSUE THREAD

**Issue by justinmk** [junegunn/fzf#732]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

fzf version: `0.15.6`

Piping the file in this gist causes a panic.
https://gist.github.com/anonymous/9ea47070a093c04a38911957a01705c5

    cat /file/from/gist | fzf  --header-lines=1

Without `--header-lines=1`, no panic.

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x4821a8]
  goroutine 8 [running]: panic(0x5481c0, 0xc4200120b0)
  /go1.7/src/runtime/panic.go:500 +0x1a1
  github.com/junegunn/fzf/src.(*Result).colorOffsets.func1(0x4)
  /fzf/gopath/src/github.com/junegunn/fzf/src/result.go:162 +0x308
  github.com/junegunn/fzf/src.(*Result).colorOffsets(0xc42003bd08, 0x831d10,
  0x0, 0x0, 0x0, 0x0, 0x300000000, 0xc42003bb01, 0x8, 0x0)
  /fzf/gopath/src/github.com/junegunn/fzf/src/result.go:174 +0x558
  github.com/junegunn/fzf/src.(*Terminal).printHighlighted(0xc420076a00,
  0xc42003bd08, 0xa00000000, 0xc4200f2600)
  /fzf/gopath/src/github.com/junegunn/fzf/src/terminal.go:725 +0x1d8
  github.com/junegunn/fzf/src.(*Terminal).printHeader(0xc420076a00)
  /fzf/gopath/src/github.com/junegunn/fzf/src/terminal.go:596 +0x2e3
  github.com/junegunn/fzf/src.(*Terminal).Loop(0xc420076a00)
  /fzf/gopath/src/github.com/junegunn/fzf/src/terminal.go:1039 +0x290 created by
  github.com/junegunn/fzf/src.Run
  /fzf/gopath/src/github.com/junegunn/fzf/src/core.go:205 +0xbc7
```

**Comment by junegunn** [comment]
You have `--no-color` or equivalent in your $FZF_DEFAULT_OPTS, right?

**Comment by junegunn** [comment]
Should be fixed now. I'll release a new version shortly. Thanks for the report.
